# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('choice_ids', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
