# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20160920_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='choice_ids',
            field=models.CharField(max_length=400),
        ),
    ]
